version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./aiobs.db}
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
